const buttonStyle = {
  mainoption: {
    width: "22vw",
    height: "26vh",
    borderWidh: "3px",
    borderRadius: "2%",
    color: "white",
    fontSize: "20px",
    outlinedPrimary: "white",
  },
  mainlabel: {
    flexDirection: "column",
    justifyContent: "spaceBetween",
  },
  authpage: {
    width: "300px",
    height: "50px",
    borderWidth: "2px",
    borderRadius: "5%",
    color: "white",
    fontSize: "20px",
    outlinedPrimary: "white",
    fontFamily: "sans-serif",
    fontWeight: "bold",
    top: "20px",
  },
  icon: {
    width: 200,
    height: 200,
    fontSize: "large",
  },
  auth: {
    width: "10vw",
    height: "8vh",
    fontSize: "30px",
    textAlign: "center",
    color: "white",
  },
  points: {
    width: "250px",
    height: "80px",
    fontSize: "40px",
    textAlign: "center",
    color: "white",
    fontWeight: "bold",
    borderWidth: "2px",
  },
  authBold: {
    width: "200px",
    height: "60px",
    fontSize: "30px",
    textAlign: "center",
    color: "white",
    background: "white",
  },
  weightOption: {
    fontSize: "30px",
  },
  buddy: {
    width: "200px",
    height: "50px",
    borderWidth: "5px",
    margin: "auto",
    outlinedPrimary: "white",
    color: "#137cbd",
    fontSize: "20px",
  },
  matchsendmessage: {
    height: "5vh",
    backgroundColor: "#137cbd",
    color: "white",
    "&:hover": {
      border: "2px solid #137cbd",
      color: "#137cbd",
      backgroundColor: "#FCD8F4",
    },
  },
};

export default buttonStyle;
